######################## default configuration ####################
baseURL = "https://aperturelabsdemo.netlify.app/"
title = "Aperture Labs"
theme = "bigspring"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "aperturelabsdemo" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "G-C04WW464N4" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true